export const slider_items = [
  {
    title: "Aromas of the Earth:",
    color: "#6F4E37",
    subTitle: "Sustainable Coffee Farming at its Finest",
    text: "Oran Agri chain Limited offers premium, sustainably grown coffee beans with a focus on taste, aroma and work closely with local farmers to promote environmentally-friendly methods.",
    src: "/slider/coffee.png",
    alt: "coffee beans",
  },
  {
    title: "Green Pastures:",
    color: "#9ACD32",
    subTitle: "Where Quality Beef and Sustainable Farming Meet",
    text: "Oran Agri chain Limited offers high-quality, natural feed for cows to improve their health and productivity. We prioritize animal welfare and sustainable farming in our practices, and work closely with local farmers.",
    src: "/slider/cow.png",
    alt: "cow",
  },
  {
    title: "Farm-Fresh Feathers:",
    color: "#F8F4C0",
    subTitle: "Raising Happy Chickens for Delicious Eggs",
    text: "Oran Agri chain Limited offers natural, high-quality chicken products raised sustainably and humanely. We prioritize animal welfare and sustainable farming in our operations.",
    src: "/slider/chicken.png",
    alt: "chicken",
  },
  {
    title: "Kernels of Excellence:",
    color: "#F9D142",
    subTitle: "Growing the Finest Corn on Our Family Farm",
    text: "Oran Agri chain Limited offers fresh, high-quality maize grown sustainably with a focus on taste, nutritional value and environmental responsibility.",
    src: "/slider/maize.png",
    alt: "maize",
  },
  {
    title: "Sweet Success:",
    color: "#f1b43e",
    subTitle: "Pure, Natural Honey from our Hive to Your Table",
    text: "Oran Agri chain Limited offers pure, high-quality honey from sustainable sources. Our honey is natural, carefully harvested and packaged to maintain its flavor and nutritional value. We prioritize bee welfare and environmental preservation in our practices.",
    src: "/slider/honey.png",
    alt: "honey",
  },
  {
    title: "Growing Strong:",
    color: "#6F4E37",
    subTitle: "The Best Fertilizer for a Thriving Garden and Farm",
    text: "Oran Agri chain Limited offers sustainable fertilizers for gardens and farms. Our environmentally-friendly products are made with natural and organic ingredients for safety and effectiveness. We support rural development by working closely with local farmers.",
    src: "/slider/fertilisers.png",
    alt: "fertilisers",
  },
  {
    title: "Green Banana Growers:",
    color: "#FFE135",
    subTitle:
      "Where Quality and Sustainability are at the Heart of Our Harvest",
    text: "Oran Agri chain Limited provides fresh, high-quality bananas grown sustainably. Our bananas are carefully selected and harvested to ensure the best taste and nutritional value. ",
    src: "/slider/banana.png",
    alt: "banana",
  },
];
